### ISSUE TITLE
error in metagenemark

### ISSUE THREAD

**Issue by top334** [gatech-genemark/GeneMark-EP-plus#2]
I have install the metagenemark on linux64, and I have done “cp gm_key ~/.gm_key”. It still have a error when run the shell. And I search online didn’t find the similar situation.
The shell codes is:
gmhmmp -m MetaGeneMark_v1.mod -a -k -f G -o gene.gff ./04_metaSPAdes/contigs.fasta 2>r4.metagenemark.err

the error message is:
gmhmmp: error, on open file MetaGeneMark_v1.mod

the category of the mgm is as follow
![2](https://user-images.githubusercontent.com/62991456/109150153-6e5e9900-77a3-11eb-91e9-63bacce795a3.png)

**Comment by tomasbruna** [comment]
Hello, please contact Alex Lomsadze (http://exon.gatech.edu/GeneMark/contact.html) with this issue, he's maintaining MetaGeneMark and should be able to help.

**Comment by top334** [comment]
OK thank you
