### ISSUE TITLE
Error Genemark accessory script generateReport.py

### ISSUE THREAD

**Issue by thakurpk** [gatech-genemark/GeneMark-EP-plus#3]
Hi Guys,

I want to generate for genemark output gtf. For the same, I am using generateReport.py scripts
I am getting following error,
Traceback (most recent call last):
File "generateReport.py", line 18, in
import statistics.predictionAnalysis as analysis
ModuleNotFoundError: No module named 'statistics.predictionAnalysis'; 'statistics' is not a package
I don't know, how to deal this error.
Thank you very much in advance for your time.

**Comment by tomasbruna** [comment]
Answered in https://github.com/Gaius-Augustus/BRAKER/issues/358
