### ISSUE TITLE
Error installing GeneMark-ESETEP

### ISSUE THREAD

**Issue by ShailNair** [gatech-genemark/GeneMark-EP-plus#5]
Hi,

I  installed the latest version of GeneMark-ESETEP on centos-7 (x64). When i run **bash** check_install.bash**
I get the following error:
Checking GeneMark-ES installation
Checking Perl setup
All required Perl modules were found
Checking GeneMark.hmm setup
**File gmhmme3 is not an executable or does not exist**

but gmhmme3 exist in the GeneMark-ESETEP directory and also the .gm_key in home directory

**Comment by tomasbruna** [comment]
Did you try to execute `gmhmme3` directly (just with `./gmhmme3`)? What message does that give?

**Comment by ShailNair** [comment]
I changed the directory to the genemarks directory containing gmhmme3 file. 

`gmhmme3
**Command not found**`


`bash gmhmme3
**Unable to execute binary**`

changing the permission of file `chmod +x gmhmme3` did not make any difference.

Meanwhile, I used the same genemarks package on my ubuntu virtual machine and did not see this error.

**Comment by tomasbruna** [comment]
You need to run it like this

    ./gmhmme3

Without the `./` symbol, Linux will look for gmhmme3 in your [$PATH](http://www.linfo.org/path_env_var.html).

**Comment by ShailNair** [comment]
`gmhmme3`
`No such file or directory`

I have added the $PATH to bashrc file
`export PATH=/home/GeneMark-ESETEP.4.69`

Do in need to SET gmhmme3 PATH?

**Comment by tomasbruna** [comment]
No need for adjusting the PATH, just use the "./" prefix when running the binary.

**Comment by ShailNair** [comment]
Thanks. it did work. Strangely, `check_install.bash` also ran without error, which before through error from the same working directory. 

Thank you.
